[workspace]
resolver = "3"
members = ["crates/parlar", "crates/parlar-moonshine", "crates/parlard"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"
repository = "https://github.com/avifenesh/parlar"
homepage = "https://github.com/avifenesh/parlar"
rust-version = "1.85"

[profile.release]
lto = "thin"
codegen-units = 4
